# This .pri file includes all files that do not use Graphviz
INCLUDEPATH += $$PWD

include(boost_graph_tutorial_no_graphviz_bundled_edges_and_vertices.pri)
include(boost_graph_tutorial_no_graphviz_bundled_vertices.pri)
include(boost_graph_tutorial_no_graphviz_custom_and_selectable_edges_and_vertices.pri)
include(boost_graph_tutorial_no_graphviz_custom_and_selectable_vertices.pri)
include(boost_graph_tutorial_no_graphviz_custom_edges_and_vertices.pri)
include(boost_graph_tutorial_no_graphviz_custom_vertices.pri)
include(boost_graph_tutorial_no_graphviz_helper.pri)
include(boost_graph_tutorial_no_graphviz_misc.pri)
include(boost_graph_tutorial_no_graphviz_named_and_selectable_vertices.pri)
include(boost_graph_tutorial_no_graphviz_named_edges_and_vertices.pri)
include(boost_graph_tutorial_no_graphviz_named_graph.pri)
include(boost_graph_tutorial_no_graphviz_named_vertices.pri)
include(boost_graph_tutorial_no_graphviz_no_properties.pri)
include(boost_graph_tutorial_no_graphviz_tutorial.pri)
include(boost_graph_tutorial_no_graphviz_unsure.pri)
