INCLUDEPATH += $$PWD

# .impl files are the clean tutorial code snippets,
# without header guards and other housekeeping
OTHER_FILES += \
    $$PWD/add_bundled_edge_demo.impl \
    $$PWD/add_bundled_vertex_demo.impl \
    $$PWD/add_custom_and_selectable_edge_between_vertices_demo.impl \
    $$PWD/add_custom_and_selectable_edge_demo.impl \
    $$PWD/add_custom_and_selectable_vertex_demo.impl \
    $$PWD/add_custom_edge_between_vertices_demo.impl \
    $$PWD/add_custom_edge_demo.impl \
    $$PWD/add_custom_vertex_demo.impl \
    $$PWD/add_edge_between_named_vertices_demo.impl \
    $$PWD/add_edge_between_selected_vertices_demo.impl \
    $$PWD/add_edge_demo.impl \
    $$PWD/add_named_and_selectable_vertex_demo.impl \
    $$PWD/add_named_edge_between_vertices_demo.impl \
    $$PWD/add_named_edge_demo.impl \
    $$PWD/add_named_vertex_demo.impl \
    $$PWD/add_vertex_demo.impl \
    $$PWD/clear_first_vertex_with_name_demo.impl \
    $$PWD/count_directed_graph_connected_components_demo.impl \
    $$PWD/count_edges_with_selectedness_demo.impl \
    $$PWD/count_undirected_graph_connected_components_demo.impl \
    $$PWD/count_vertices_with_name_demo.impl \
    $$PWD/count_vertices_with_selectedness_demo.impl \
    $$PWD/create_all_direct_neighbour_custom_and_selectable_edges_and_vertices_subgraphs_demo.impl \
    $$PWD/create_all_direct_neighbour_custom_and_selectable_vertices_subgraphs_demo.impl \
    $$PWD/create_all_direct_neighbour_custom_edges_and_vertices_subgraphs_demo.impl \
    $$PWD/create_all_direct_neighbour_custom_vertices_subgraphs_demo.impl \
    $$PWD/create_all_direct_neighbour_named_edges_and_vertices_subgraphs_demo.impl \
    $$PWD/create_all_direct_neighbour_named_vertices_subgraphs_demo.impl \
    $$PWD/create_all_direct_neighbour_subgraphs_demo.impl \
    $$PWD/create_bundled_edges_and_vertices_k3_graph_demo.impl \
    $$PWD/create_bundled_edges_and_vertices_markov_chain_demo.impl \
    $$PWD/create_bundled_vertices_k2_graph_demo.impl \
    $$PWD/create_bundled_vertices_markov_chain_demo.impl \
    $$PWD/create_custom_and_selectable_edges_and_vertices_k2_graph_demo.impl \
    $$PWD/create_custom_and_selectable_edges_and_vertices_k3_graph_demo.impl \
    $$PWD/create_custom_and_selectable_edges_and_vertices_markov_chain_demo.impl \
    $$PWD/create_custom_and_selectable_edges_and_vertices_path_graph_demo.impl \
    $$PWD/create_custom_and_selectable_edges_and_vertices_petersen_graph_demo.impl \
    $$PWD/create_custom_and_selectable_vertices_k2_graph_demo.impl \
    $$PWD/create_custom_and_selectable_vertices_k3_graph_demo.impl \
    $$PWD/create_custom_and_selectable_vertices_markov_chain_demo.impl \
    $$PWD/create_custom_and_selectable_vertices_path_graph_demo.impl \
    $$PWD/create_custom_and_selectable_vertices_petersen_graph_demo.impl \
    $$PWD/create_custom_edges_and_vertices_k2_graph_demo.impl \
    $$PWD/create_custom_edges_and_vertices_k3_graph_demo.impl \
    $$PWD/create_custom_edges_and_vertices_markov_chain_demo.impl \
    $$PWD/create_custom_edges_and_vertices_path_graph_demo.impl \
    $$PWD/create_custom_edges_and_vertices_petersen_graph_demo.impl \
    $$PWD/create_custom_vertices_k2_graph_demo.impl \
    $$PWD/create_custom_vertices_k3_graph_demo.impl \
    $$PWD/create_custom_vertices_markov_chain_demo.impl \
    $$PWD/create_custom_vertices_path_graph_demo.impl \
    $$PWD/create_custom_vertices_petersen_graph_demo.impl \
    $$PWD/create_direct_neighbour_custom_and_selectable_edges_and_vertices_subgraph_demo.impl \
    $$PWD/create_direct_neighbour_custom_and_selectable_vertices_subgraph_demo.impl \
    $$PWD/create_direct_neighbour_custom_edges_and_vertices_subgraph_demo.impl \
    $$PWD/create_direct_neighbour_custom_vertices_subgraph_demo.impl \
    $$PWD/create_direct_neighbour_named_edges_and_vertices_subgraph_demo.impl \
    $$PWD/create_direct_neighbour_named_vertices_subgraph_demo.impl \
    $$PWD/create_direct_neighbour_subgraph_demo.impl \
    $$PWD/create_empty_directed_bundled_edges_and_vertices_graph_demo.impl \
    $$PWD/create_empty_directed_custom_and_selectable_edges_and_vertices_graph_demo.impl \
    $$PWD/create_empty_directed_custom_and_selectable_vertices_graph_demo.impl \
    $$PWD/create_empty_directed_custom_edges_and_vertices_graph_demo.impl \
    $$PWD/create_empty_directed_custom_vertices_graph_demo.impl \
    $$PWD/create_empty_directed_graph_demo.impl \
    $$PWD/create_empty_directed_graph_with_graph_name_demo.impl \
    $$PWD/create_empty_directed_named_and_selectable_vertices_graph_demo.impl \
    $$PWD/create_empty_directed_named_edges_and_vertices_graph_demo.impl \
    $$PWD/create_empty_directed_named_vertices_graph_demo.impl \
    $$PWD/create_empty_undirected_bundled_edges_and_vertices_graph_demo.impl \
    $$PWD/create_empty_undirected_custom_and_selectable_edges_and_vertices_graph_demo.impl \
    $$PWD/create_empty_undirected_custom_and_selectable_vertices_graph_demo.impl \
    $$PWD/create_empty_undirected_custom_edges_and_vertices_graph_demo.impl \
    $$PWD/create_empty_undirected_custom_vertices_graph_demo.impl \
    $$PWD/create_empty_undirected_graph_demo.impl \
    $$PWD/create_empty_undirected_graph_with_graph_name_demo.impl \
    $$PWD/create_empty_undirected_named_and_selectable_vertices_graph_demo.impl \
    $$PWD/create_empty_undirected_named_edges_and_vertices_graph_demo.impl \
    $$PWD/create_empty_undirected_named_vertices_graph_demo.impl \
    $$PWD/create_k2_graph_demo.impl \
    $$PWD/create_k2_graph_with_graph_name_demo.impl \
    $$PWD/create_k3_graph_demo.impl \
    $$PWD/create_markov_chain_demo.impl \
    $$PWD/create_markov_chain_with_graph_name_demo.impl \
    $$PWD/create_named_edges_and_vertices_k2_graph_demo.impl \
    $$PWD/create_named_edges_and_vertices_k3_graph_demo.impl \
    $$PWD/create_named_edges_and_vertices_markov_chain_demo.impl \
    $$PWD/create_named_edges_and_vertices_path_graph_demo.impl \
    $$PWD/create_named_edges_and_vertices_petersen_graph_demo.impl \
    $$PWD/create_named_vertices_k2_graph_demo.impl \
    $$PWD/create_named_vertices_k3_graph_demo.impl \
    $$PWD/create_named_vertices_markov_chain_demo.impl \
    $$PWD/create_named_vertices_path_graph_demo.impl \
    $$PWD/create_named_vertices_petersen_graph_demo.impl \
    $$PWD/create_path_graph_demo.impl \
    $$PWD/create_petersen_graph_demo.impl \
    $$PWD/find_first_bundled_edge_with_my_edge_demo.impl \
    $$PWD/find_first_bundled_vertex_with_my_vertex_demo.impl \
    $$PWD/find_first_custom_edge_with_my_edge_demo.impl \
    $$PWD/find_first_custom_vertex_with_my_vertex_demo.impl \
    $$PWD/find_first_edge_with_name_demo.impl \
    $$PWD/find_first_vertex_with_name_demo.impl \
    $$PWD/get_edge_between_vertices_demo.impl \
    $$PWD/get_edge_descriptors_demo.impl \
    $$PWD/get_edge_iterators_demo.impl \
    $$PWD/get_edge_name_demo.impl \
    $$PWD/get_edge_names_demo.impl \
    $$PWD/get_edge_selectedness_demo.impl \
    $$PWD/get_first_vertex_with_name_out_degree_demo.impl \
    $$PWD/get_graph_name_demo.impl \
    $$PWD/get_my_bundled_edge_demo.impl \
    $$PWD/get_my_bundled_edges_demo.impl \
    $$PWD/get_my_custom_edge_demo.impl \
    $$PWD/get_my_custom_edges_demo.impl \
    $$PWD/get_my_custom_vertex_demo.impl \
    $$PWD/get_my_custom_vertexes_demo.impl \
    $$PWD/get_n_edges_demo.impl \
    $$PWD/get_n_vertices_demo.impl \
    $$PWD/get_vertex_descriptors_demo.impl \
    $$PWD/get_vertex_iterators_demo.impl \
    $$PWD/get_vertex_name_demo.impl \
    $$PWD/get_vertex_names_demo.impl \
    $$PWD/get_vertex_out_degrees_demo.impl \
    $$PWD/get_vertex_selectedness_demo.impl \
    $$PWD/get_vertex_selectednesses_demo.impl \
    $$PWD/has_bundled_edge_with_my_edge_demo.impl \
    $$PWD/has_bundled_vertex_with_my_vertex_demo.impl \
    $$PWD/has_edge_with_my_edge_demo.impl \
    $$PWD/has_custom_vertex_with_my_vertex_demo.impl \
    $$PWD/has_edge_between_vertices_demo.impl \
    $$PWD/has_edge_with_name_demo.impl \
    $$PWD/has_vertex_with_name_demo.impl \
    $$PWD/is_custom_vertices_isomorphic_demo.impl \
    $$PWD/is_isomorphic_demo.impl \
    $$PWD/is_named_vertices_isomorphic_demo.impl \
    $$PWD/is_named_vertices_isomorphic.impl \
    $$PWD/is_regular_file.impl \
    $$PWD/is_valid_dot_file.impl \
    $$PWD/load_directed_bundled_edges_and_vertices_graph_from_dot_demo.impl \
    $$PWD/load_directed_bundled_edges_and_vertices_graph_from_dot.impl \
    $$PWD/load_directed_bundled_vertices_graph_from_dot_demo.impl \
    $$PWD/load_directed_bundled_vertices_graph_from_dot.impl \
    $$PWD/load_directed_custom_and_selectable_edges_and_vertices_graph_from_dot_demo.impl \
    $$PWD/load_directed_custom_and_selectable_edges_and_vertices_graph_from_dot.impl \
    $$PWD/load_directed_custom_and_selectable_vertices_graph_from_dot_demo.impl \
    $$PWD/load_directed_custom_and_selectable_vertices_graph_from_dot.impl \
    $$PWD/load_directed_custom_edges_and_vertices_graph_from_dot_demo.impl \
    $$PWD/load_directed_custom_edges_and_vertices_graph_from_dot.impl \
    $$PWD/load_directed_custom_vertices_graph_from_dot_demo.impl \
    $$PWD/load_directed_custom_vertices_graph_from_dot.impl \
    $$PWD/load_directed_graph_from_dot_demo.impl \
    $$PWD/load_directed_graph_from_dot.impl \
    $$PWD/load_directed_graph_with_graph_name_from_dot_demo.impl \
    $$PWD/load_directed_graph_with_graph_name_from_dot.impl \
    $$PWD/load_directed_named_edges_and_vertices_graph_from_dot_demo.impl \
    $$PWD/load_directed_named_edges_and_vertices_graph_from_dot.impl \
    $$PWD/load_directed_named_vertices_graph_from_dot_demo.impl \
    $$PWD/load_directed_named_vertices_graph_from_dot.impl \
    $$PWD/load_undirected_bundled_edges_and_vertices_graph_from_dot_demo.impl \
    $$PWD/load_undirected_bundled_edges_and_vertices_graph_from_dot.impl \
    $$PWD/load_undirected_bundled_vertices_graph_from_dot_demo.impl \
    $$PWD/load_undirected_bundled_vertices_graph_from_dot.impl \
    $$PWD/load_undirected_custom_and_selectable_edges_and_vertices_graph_from_dot_demo.impl \
    $$PWD/load_undirected_custom_and_selectable_edges_and_vertices_graph_from_dot.impl \
    $$PWD/load_undirected_custom_and_selectable_vertices_graph_from_dot_demo.impl \
    $$PWD/load_undirected_custom_and_selectable_vertices_graph_from_dot.impl \
    $$PWD/load_undirected_custom_edges_and_vertices_graph_from_dot_demo.impl \
    $$PWD/load_undirected_custom_edges_and_vertices_graph_from_dot.impl \
    $$PWD/load_undirected_custom_vertices_graph_from_dot_demo.impl \
    $$PWD/load_undirected_custom_vertices_graph_from_dot.impl \
    $$PWD/load_undirected_graph_from_dot_demo.impl \
    $$PWD/load_undirected_graph_from_dot.impl \
    $$PWD/load_undirected_graph_with_graph_name_from_dot_demo.impl \
    $$PWD/load_undirected_graph_with_graph_name_from_dot.impl \
    $$PWD/load_undirected_named_edges_and_vertices_graph_from_dot_demo.impl \
    $$PWD/load_undirected_named_edges_and_vertices_graph_from_dot.impl \
    $$PWD/load_undirected_named_vertices_graph_from_dot_demo.impl \
    $$PWD/load_undirected_named_vertices_graph_from_dot.impl \
    $$PWD/make_bundled_edges_writer.impl \
    $$PWD/make_bundled_vertices_writer.impl \
    $$PWD/make_custom_and_selectable_vertices_writer.impl \
    $$PWD/my_bundled_edge.impl \
    $$PWD/my_bundled_vertex.impl \
    $$PWD/my_custom_edge.impl \
    $$PWD/my_custom_vertex.impl \
    $$PWD/named_vertex_invariant.impl \
    $$PWD/no_matching_function_for_call_to_clear_out_edges.impl \
    $$PWD/property_not_found_node_id.impl \
    $$PWD/remove_edge_between_vertices_with_names_demo.impl \
    $$PWD/remove_edge_between_vertices_with_names.impl \
    $$PWD/remove_first_edge_with_name_demo.impl \
    $$PWD/remove_first_edge_with_name.impl \
    $$PWD/remove_first_vertex_with_name_demo.impl \
    $$PWD/remove_first_vertex_with_name.impl \
    $$PWD/save_bundled_edges_and_vertices_graph_to_dot_demo.impl \
    $$PWD/save_bundled_edges_and_vertices_graph_to_dot.impl \
    $$PWD/save_bundled_vertices_graph_to_dot.impl \
    $$PWD/save_custom_and_selectable_edges_and_vertices_graph_to_dot_demo.impl \
    $$PWD/save_custom_and_selectable_edges_and_vertices_graph_to_dot.impl \
    $$PWD/save_custom_and_selectable_vertices_graph_to_dot_demo.impl \
    $$PWD/save_custom_and_selectable_vertices_graph_to_dot.impl \
    $$PWD/save_custom_edges_and_vertices_graph_to_dot_demo.impl \
    $$PWD/save_custom_edges_and_vertices_graph_to_dot.impl \
    $$PWD/save_custom_vertices_graph_to_dot_demo.impl \
    $$PWD/save_custom_vertices_graph_to_dot.impl \
    $$PWD/save_custom_vertices_graph_to_dot.impl \
    $$PWD/save_graph_to_dot_demo.impl \
    $$PWD/save_graph_to_dot.impl \
    $$PWD/save_graph_with_graph_name_to_dot.impl \
    $$PWD/save_named_edges_and_vertices_graph_to_dot.impl \
    $$PWD/save_named_edges_and_vertices_graph_to_dot.impl \
    $$PWD/save_named_vertices_graph_to_dot_demo.impl \
    $$PWD/save_named_vertices_graph_to_dot.impl \
    $$PWD/save_named_vertices_graph_to_dot_using_lambda.impl \
    $$PWD/set_edge_name_demo.impl \
    $$PWD/set_edge_name.impl \
    $$PWD/set_edge_selectedness_demo.impl \
    $$PWD/set_edge_selectedness.impl \
    $$PWD/set_graph_name_demo.impl \
    $$PWD/set_graph_name.impl \
    $$PWD/set_my_bundled_edge_demo.impl \
    $$PWD/set_my_bundled_edge.impl \
    $$PWD/set_my_bundled_vertex_demo.impl \
    $$PWD/set_my_bundled_vertexes.impl \
    $$PWD/set_my_bundled_vertex.impl \
    $$PWD/set_my_custom_edge_demo.impl \
    $$PWD/set_my_custom_edge.impl \
    $$PWD/set_my_custom_vertex_demo.impl \
    $$PWD/set_my_custom_vertexes.impl \
    $$PWD/set_my_custom_vertex.impl \
    $$PWD/set_vertex_name_demo.impl \
    $$PWD/set_vertex_name.impl \
    $$PWD/set_vertex_names.impl \
    $$PWD/set_vertex_selectedness_demo.impl \
    $$PWD/set_vertex_selectedness.impl \
    $$PWD/add_edge_between_custom_vertices.impl \
    $$PWD/add_edge_between_custom_vertices_demo.impl \
    $$PWD/has_vertex_with_my_vertex.impl \
    $$PWD/has_vertex_with_my_vertex_demo.impl \
    $$PWD/select_random_vertex.impl \
    $$PWD/select_random_vertex_demo.impl
