INCLUDEPATH += $$PWD

HEADERS += \
    $$PWD/bundled_edges_writer.h \
    $$PWD/bundled_vertices_writer.h \
    $$PWD/convert_dot_to_svg.h \
    $$PWD/create_all_direct_neighbour_custom_and_selectable_edges_and_vertices_subgraphs.h \
    $$PWD/create_all_direct_neighbour_custom_and_selectable_vertices_subgraphs.h \
    $$PWD/create_all_direct_neighbour_custom_edges_and_vertices_subgraphs.h \
    $$PWD/create_all_direct_neighbour_custom_vertices_subgraphs.h \
    $$PWD/create_all_direct_neighbour_named_edges_and_vertices_subgraphs.h \
    $$PWD/create_all_direct_neighbour_named_vertices_subgraphs.h \
    $$PWD/create_all_direct_neighbour_subgraphs.h \
    $$PWD/create_bundled_edges_and_vertices_k3_graph.h \
    $$PWD/create_bundled_edges_and_vertices_markov_chain.h \
    $$PWD/create_bundled_vertices_k2_graph.h \
    $$PWD/create_bundled_vertices_markov_chain.h \
    $$PWD/create_custom_and_selectable_edges_and_vertices_k2_graph.h \
    $$PWD/create_custom_and_selectable_edges_and_vertices_k3_graph.h \
    $$PWD/create_custom_and_selectable_edges_and_vertices_markov_chain.h \
    $$PWD/create_custom_and_selectable_edges_and_vertices_path_graph.h \
    $$PWD/create_custom_and_selectable_edges_and_vertices_petersen_graph.h \
    $$PWD/create_custom_and_selectable_vertices_k2_graph.h \
    $$PWD/create_custom_and_selectable_vertices_k3_graph.h \
    $$PWD/create_custom_and_selectable_vertices_markov_chain.h \
    $$PWD/create_custom_and_selectable_vertices_path_graph.h \
    $$PWD/create_custom_and_selectable_vertices_petersen_graph.h \
    $$PWD/create_custom_edges_and_vertices_k2_graph.h \
    $$PWD/create_custom_edges_and_vertices_k3_graph.h \
    $$PWD/create_custom_edges_and_vertices_markov_chain.h \
    $$PWD/create_custom_edges_and_vertices_path_graph.h \
    $$PWD/create_custom_edges_and_vertices_petersen_graph.h \
    $$PWD/create_custom_vertices_k2_graph.h \
    $$PWD/create_custom_vertices_k3_graph.h \
    $$PWD/create_custom_vertices_markov_chain.h \
    $$PWD/create_custom_vertices_path_graph.h \
    $$PWD/create_custom_vertices_petersen_graph.h \
    $$PWD/create_direct_neighbour_custom_and_selectable_edges_and_vertices_subgraph.h \
    $$PWD/create_direct_neighbour_custom_and_selectable_vertices_subgraph.h \
    $$PWD/create_direct_neighbour_custom_edges_and_vertices_subgraph.h \
    $$PWD/create_direct_neighbour_custom_vertices_subgraph.h \
    $$PWD/create_direct_neighbour_named_edges_and_vertices_subgraph.h \
    $$PWD/create_direct_neighbour_named_vertices_subgraph.h \
    $$PWD/create_direct_neighbour_subgraph.h \
    $$PWD/create_direct_neighbour_subgraph_including_in_edges.h \
    $$PWD/create_empty_directed_bundled_edges_and_vertices_graph.h \
    $$PWD/create_empty_directed_bundled_vertices_graph.h \
    $$PWD/create_empty_directed_custom_and_selectable_edges_and_vertices_graph.h \
    $$PWD/create_empty_directed_custom_and_selectable_vertices_graph.h \
    $$PWD/create_empty_directed_custom_edges_and_vertices_graph.h \
    $$PWD/create_empty_directed_custom_vertices_graph.h \
    $$PWD/create_empty_directed_graph.h \
    $$PWD/create_empty_directed_graph_with_graph_name.h \
    $$PWD/create_empty_directed_named_and_selectable_vertices_graph.h \
    $$PWD/create_empty_directed_named_edges_and_vertices_graph.h \
    $$PWD/create_empty_directed_named_vertices_graph.h \
    $$PWD/create_empty_undirected_bundled_edges_and_vertices_graph.h \
    $$PWD/create_empty_undirected_bundled_vertices_graph.h \
    $$PWD/create_empty_undirected_custom_and_selectable_edges_and_vertices_graph.h \
    $$PWD/create_empty_undirected_custom_and_selectable_vertices_graph.h \
    $$PWD/create_empty_undirected_custom_edges_and_vertices_graph.h \
    $$PWD/create_empty_undirected_custom_vertices_graph.h \
    $$PWD/create_empty_undirected_graph.h \
    $$PWD/create_empty_undirected_graph_with_graph_name.h \
    $$PWD/create_empty_undirected_named_and_selectable_vertices_graph.h \
    $$PWD/create_empty_undirected_named_edges_and_vertices_graph.h \
    $$PWD/create_empty_undirected_named_vertices_graph.h \
    $$PWD/create_k2_graph.h \
    $$PWD/create_k2_graph_with_graph_name.h \
    $$PWD/create_k3_graph.h \
    $$PWD/create_markov_chain.h \
    $$PWD/create_markov_chain_with_graph_name.h \
    $$PWD/create_named_edges_and_vertices_k2_graph.h \
    $$PWD/create_named_edges_and_vertices_k3_graph.h \
    $$PWD/create_named_edges_and_vertices_markov_chain.h \
    $$PWD/create_named_edges_and_vertices_path_graph.h \
    $$PWD/create_named_edges_and_vertices_petersen_graph.h \
    $$PWD/create_named_vertices_k2_graph.h \
    $$PWD/create_named_vertices_k3_graph.h \
    $$PWD/create_named_vertices_markov_chain.h \
    $$PWD/create_named_vertices_path_graph.h \
    $$PWD/create_named_vertices_petersen_graph.h \
    $$PWD/create_nasty_directed_bundled_edges_and_vertices_graph.h \
    $$PWD/create_nasty_directed_bundled_vertices_graph.h \
    $$PWD/create_nasty_directed_custom_and_selectable_vertices_graph.h \
    $$PWD/create_nasty_directed_custom_edges_and_vertices_graph.h \
    $$PWD/create_nasty_directed_custom_vertices_graph.h \
    $$PWD/create_nasty_directed_named_vertices_graph.h \
    $$PWD/create_nasty_undirected_bundled_edges_and_vertices_graph.h \
    $$PWD/create_nasty_undirected_custom_and_selectable_vertices_graph.h \
    $$PWD/create_nasty_undirected_custom_edges_and_vertices_graph.h \
    $$PWD/create_path_graph.h \
    $$PWD/create_petersen_graph.h \
    $$PWD/create_tutorial_chapters_graph.h \
    $$PWD/create_tutorial_subchapters_graph.h \
    $$PWD/graphviz_decode.h \
    $$PWD/graphviz_encode.h \
    $$PWD/is_graphviz_friendly.h \
    $$PWD/is_valid_dot_file.h \
    $$PWD/load_directed_bundled_edges_and_vertices_graph_from_dot.h \
    $$PWD/load_directed_bundled_vertices_graph_from_dot.h \
    $$PWD/load_directed_custom_and_selectable_edges_and_vertices_graph_from_dot.h \
    $$PWD/load_directed_custom_and_selectable_vertices_graph_from_dot.h \
    $$PWD/load_directed_custom_edges_and_vertices_graph_from_dot.h \
    $$PWD/load_directed_custom_vertices_graph_from_dot.h \
    $$PWD/load_directed_graph_from_dot.h \
    $$PWD/load_directed_graph_with_graph_name_from_dot.h \
    $$PWD/load_directed_named_edges_and_vertices_graph_from_dot.h \
    $$PWD/load_directed_named_vertices_graph_from_dot.h \
    $$PWD/load_undirected_bundled_edges_and_vertices_graph_from_dot.h \
    $$PWD/load_undirected_bundled_vertices_graph_from_dot.h \
    $$PWD/load_undirected_custom_and_selectable_edges_and_vertices_graph_from_dot.h \
    $$PWD/load_undirected_custom_and_selectable_vertices_graph_from_dot.h \
    $$PWD/load_undirected_custom_edges_and_vertices_graph_from_dot.h \
    $$PWD/load_undirected_custom_vertices_graph_from_dot.h \
    $$PWD/load_undirected_graph_from_dot.h \
    $$PWD/load_undirected_graph_with_graph_name_from_dot.h \
    $$PWD/load_undirected_named_edges_and_vertices_graph_from_dot.h \
    $$PWD/load_undirected_named_vertices_graph_from_dot.h \
    $$PWD/property_not_found_node_id.h \
    $$PWD/save_bundled_edges_and_vertices_graph_to_dot.h \
    $$PWD/save_bundled_vertices_graph_to_dot.h \
    $$PWD/save_custom_and_selectable_edges_and_vertices_graph_to_dot.h \
    $$PWD/save_custom_and_selectable_vertices_graph_to_dot.h \
    $$PWD/save_custom_edges_and_vertices_graph_to_dot.h \
    $$PWD/save_custom_vertices_graph_to_dot.h \
    $$PWD/save_graph_to_dot.h \
    $$PWD/save_graph_with_graph_name_to_dot.h \
    $$PWD/save_named_edges_and_vertices_graph_to_dot.h \
    $$PWD/save_named_vertices_graph_to_dot.h

SOURCES += \
    $$PWD/bundled_edges_writer.cpp \
    $$PWD/bundled_vertices_writer.cpp \
    $$PWD/convert_dot_to_svg.cpp \
    $$PWD/create_all_direct_neighbour_custom_and_selectable_edges_and_vertices_subgraphs.cpp \
    $$PWD/create_all_direct_neighbour_custom_and_selectable_vertices_subgraphs.cpp \
    $$PWD/create_all_direct_neighbour_custom_edges_and_vertices_subgraphs.cpp \
    $$PWD/create_all_direct_neighbour_custom_vertices_subgraphs.cpp \
    $$PWD/create_all_direct_neighbour_named_edges_and_vertices_subgraphs.cpp \
    $$PWD/create_all_direct_neighbour_named_vertices_subgraphs.cpp \
    $$PWD/create_all_direct_neighbour_subgraphs.cpp \
    $$PWD/create_bundled_edges_and_vertices_k3_graph.cpp \
    $$PWD/create_bundled_edges_and_vertices_markov_chain.cpp \
    $$PWD/create_bundled_vertices_k2_graph.cpp \
    $$PWD/create_bundled_vertices_markov_chain.cpp \
    $$PWD/create_custom_and_selectable_edges_and_vertices_k2_graph.cpp \
    $$PWD/create_custom_and_selectable_edges_and_vertices_k3_graph.cpp \
    $$PWD/create_custom_and_selectable_edges_and_vertices_markov_chain.cpp \
    $$PWD/create_custom_and_selectable_edges_and_vertices_path_graph.cpp \
    $$PWD/create_custom_and_selectable_edges_and_vertices_petersen_graph.cpp \
    $$PWD/create_custom_and_selectable_vertices_k2_graph.cpp \
    $$PWD/create_custom_and_selectable_vertices_k3_graph.cpp \
    $$PWD/create_custom_and_selectable_vertices_markov_chain.cpp \
    $$PWD/create_custom_and_selectable_vertices_path_graph.cpp \
    $$PWD/create_custom_and_selectable_vertices_petersen_graph.cpp \
    $$PWD/create_custom_edges_and_vertices_k2_graph.cpp \
    $$PWD/create_custom_edges_and_vertices_k3_graph.cpp \
    $$PWD/create_custom_edges_and_vertices_markov_chain.cpp \
    $$PWD/create_custom_edges_and_vertices_path_graph.cpp \
    $$PWD/create_custom_edges_and_vertices_petersen_graph.cpp \
    $$PWD/create_custom_vertices_k2_graph.cpp \
    $$PWD/create_custom_vertices_k3_graph.cpp \
    $$PWD/create_custom_vertices_markov_chain.cpp \
    $$PWD/create_custom_vertices_path_graph.cpp \
    $$PWD/create_custom_vertices_petersen_graph.cpp \
    $$PWD/create_direct_neighbour_custom_and_selectable_edges_and_vertices_subgraph.cpp \
    $$PWD/create_direct_neighbour_custom_and_selectable_vertices_subgraph.cpp \
    $$PWD/create_direct_neighbour_custom_edges_and_vertices_subgraph.cpp \
    $$PWD/create_direct_neighbour_custom_vertices_subgraph.cpp \
    $$PWD/create_direct_neighbour_named_edges_and_vertices_subgraph.cpp \
    $$PWD/create_direct_neighbour_named_vertices_subgraph.cpp \
    $$PWD/create_direct_neighbour_subgraph.cpp \
    $$PWD/create_direct_neighbour_subgraph_including_in_edges.cpp \
    $$PWD/create_empty_directed_bundled_edges_and_vertices_graph.cpp \
    $$PWD/create_empty_directed_bundled_vertices_graph.cpp \
    $$PWD/create_empty_directed_custom_and_selectable_edges_and_vertices_graph.cpp \
    $$PWD/create_empty_directed_custom_and_selectable_vertices_graph.cpp \
    $$PWD/create_empty_directed_custom_edges_and_vertices_graph.cpp \
    $$PWD/create_empty_directed_custom_vertices_graph.cpp \
    $$PWD/create_empty_directed_graph.cpp \
    $$PWD/create_empty_directed_graph_with_graph_name.cpp \
    $$PWD/create_empty_directed_named_and_selectable_vertices_graph.cpp \
    $$PWD/create_empty_directed_named_edges_and_vertices_graph.cpp \
    $$PWD/create_empty_directed_named_vertices_graph.cpp \
    $$PWD/create_empty_undirected_bundled_edges_and_vertices_graph.cpp \
    $$PWD/create_empty_undirected_bundled_vertices_graph.cpp \
    $$PWD/create_empty_undirected_custom_and_selectable_edges_and_vertices_graph.cpp \
    $$PWD/create_empty_undirected_custom_and_selectable_vertices_graph.cpp \
    $$PWD/create_empty_undirected_custom_edges_and_vertices_graph.cpp \
    $$PWD/create_empty_undirected_custom_vertices_graph.cpp \
    $$PWD/create_empty_undirected_graph.cpp \
    $$PWD/create_empty_undirected_graph_with_graph_name.cpp \
    $$PWD/create_empty_undirected_named_and_selectable_vertices_graph.cpp \
    $$PWD/create_empty_undirected_named_edges_and_vertices_graph.cpp \
    $$PWD/create_empty_undirected_named_vertices_graph.cpp \
    $$PWD/create_k2_graph.cpp \
    $$PWD/create_k2_graph_with_graph_name.cpp \
    $$PWD/create_k3_graph.cpp \
    $$PWD/create_markov_chain.cpp \
    $$PWD/create_markov_chain_with_graph_name.cpp \
    $$PWD/create_named_edges_and_vertices_k2_graph.cpp \
    $$PWD/create_named_edges_and_vertices_k3_graph.cpp \
    $$PWD/create_named_edges_and_vertices_markov_chain.cpp \
    $$PWD/create_named_edges_and_vertices_path_graph.cpp \
    $$PWD/create_named_edges_and_vertices_petersen_graph.cpp \
    $$PWD/create_named_vertices_k2_graph.cpp \
    $$PWD/create_named_vertices_k3_graph.cpp \
    $$PWD/create_named_vertices_markov_chain.cpp \
    $$PWD/create_named_vertices_path_graph.cpp \
    $$PWD/create_named_vertices_petersen_graph.cpp \
    $$PWD/create_nasty_directed_bundled_edges_and_vertices_graph.cpp \
    $$PWD/create_nasty_directed_bundled_vertices_graph.cpp \
    $$PWD/create_nasty_directed_custom_and_selectable_vertices_graph.cpp \
    $$PWD/create_nasty_directed_custom_edges_and_vertices_graph.cpp \
    $$PWD/create_nasty_directed_custom_vertices_graph.cpp \
    $$PWD/create_nasty_directed_named_vertices_graph.cpp \
    $$PWD/create_nasty_undirected_bundled_edges_and_vertices_graph.cpp \
    $$PWD/create_nasty_undirected_custom_and_selectable_vertices_graph.cpp \
    $$PWD/create_nasty_undirected_custom_edges_and_vertices_graph.cpp \
    $$PWD/create_path_graph.cpp \
    $$PWD/create_petersen_graph.cpp \
    $$PWD/create_tutorial_chapters_graph.cpp \
    $$PWD/create_tutorial_subchapters_graph.cpp \
    $$PWD/custom_and_selectable_vertices_writer.cpp \
    $$PWD/graphviz_decode.cpp \
    $$PWD/graphviz_encode.cpp \
    $$PWD/has_dot.cpp \
    $$PWD/is_graphviz_friendly.cpp \
    $$PWD/is_isomorphic.cpp \
    $$PWD/is_named_vertices_isomorphic.cpp \
    $$PWD/is_regular_file.cpp \
    $$PWD/is_valid_dot_file.cpp \
    $$PWD/load_directed_bundled_edges_and_vertices_graph_from_dot.cpp \
    $$PWD/load_directed_bundled_vertices_graph_from_dot.cpp \
    $$PWD/load_directed_custom_and_selectable_edges_and_vertices_graph_from_dot.cpp \
    $$PWD/load_directed_custom_and_selectable_vertices_graph_from_dot.cpp \
    $$PWD/load_directed_custom_edges_and_vertices_graph_from_dot.cpp \
    $$PWD/load_directed_custom_vertices_graph_from_dot.cpp \
    $$PWD/load_directed_graph_from_dot.cpp \
    $$PWD/load_directed_graph_with_graph_name_from_dot.cpp \
    $$PWD/load_directed_named_edges_and_vertices_graph_from_dot.cpp \
    $$PWD/load_directed_named_vertices_graph_from_dot.cpp \
    $$PWD/load_undirected_bundled_edges_and_vertices_graph_from_dot.cpp \
    $$PWD/load_undirected_bundled_vertices_graph_from_dot.cpp \
    $$PWD/load_undirected_custom_and_selectable_edges_and_vertices_graph_from_dot.cpp \
    $$PWD/load_undirected_custom_and_selectable_vertices_graph_from_dot.cpp \
    $$PWD/load_undirected_custom_edges_and_vertices_graph_from_dot.cpp \
    $$PWD/load_undirected_custom_vertices_graph_from_dot.cpp \
    $$PWD/load_undirected_graph_from_dot.cpp \
    $$PWD/load_undirected_graph_with_graph_name_from_dot.cpp \
    $$PWD/load_undirected_named_edges_and_vertices_graph_from_dot.cpp \
    $$PWD/load_undirected_named_vertices_graph_from_dot.cpp \
    $$PWD/make_bundled_edges_writer.cpp \
    $$PWD/make_bundled_vertices_writer.cpp \
    $$PWD/make_custom_and_selectable_vertices_writer.cpp \
    $$PWD/property_not_found_node_id.cpp \
    $$PWD/save_bundled_edges_and_vertices_graph_to_dot.cpp \
    $$PWD/save_bundled_vertices_graph_to_dot.cpp \
    $$PWD/save_custom_and_selectable_edges_and_vertices_graph_to_dot.cpp \
    $$PWD/save_custom_and_selectable_vertices_graph_to_dot.cpp \
    $$PWD/save_custom_edges_and_vertices_graph_to_dot.cpp \
    $$PWD/save_custom_vertices_graph_to_dot.cpp \
    $$PWD/save_graph_to_dot.cpp \
    $$PWD/save_graph_with_graph_name_to_dot.cpp \
    $$PWD/save_named_edges_and_vertices_graph_to_dot.cpp \
    $$PWD/save_named_vertices_graph_to_dot.cpp \
    $$PWD/seperate_string.cpp \
    $$PWD/show_dot.cpp \
    $$PWD/add_edge_between_custom_vertices.cpp \
    $$PWD/has_vertex_with_my_vertex.cpp \
    $$PWD/create_nasty_directed_custom_and_selectable_edges_and_vertices_graph.cpp \
    $$PWD/select_random_vertex.cpp \
    $$PWD/get_edge_iterators.cpp \
    $$PWD/count_max_number_of_pieces.cpp


# .impl files are the clean tutorial code snippets,
# without header guards and other housekeeping
OTHER_FILES += \
    $$PWD/add_bundled_edge.impl \
    $$PWD/add_bundled_vertex.impl \
    $$PWD/add_custom_and_selectable_edge_between_vertices.impl \
    $$PWD/add_custom_and_selectable_edge.impl \
    $$PWD/add_custom_and_selectable_vertex.impl \
    $$PWD/add_custom_edge_between_vertices.impl \
    $$PWD/add_custom_edge.impl \
    $$PWD/add_custom_vertex.impl \
    $$PWD/add_edge_between_named_vertices.impl \
    $$PWD/add_edge_between_selected_vertices.impl \
    $$PWD/add_edge.impl \
    $$PWD/add_named_and_selectable_vertex.impl \
    $$PWD/add_named_edge_between_vertices.impl \
    $$PWD/add_named_edge.impl \
    $$PWD/add_named_vertex.impl \
    $$PWD/add_vertex.impl \
    $$PWD/bundled_edges_writer.impl \
    $$PWD/bundled_vertices_writer.impl \
    $$PWD/convert_dot_to_svg.impl \
    $$PWD/count_directed_graph_connected_components.impl \
    $$PWD/count_edges_with_selectedness.impl \
    $$PWD/count_undirected_graph_connected_components.impl \
    $$PWD/count_undirected_graph_levels.impl \
    $$PWD/count_vertices_with_name.impl \
    $$PWD/count_vertices_with_selectedness.impl \
    $$PWD/create_all_direct_neighbour_custom_and_selectable_edges_and_vertices_subgraphs.impl \
    $$PWD/create_all_direct_neighbour_custom_and_selectable_vertices_subgraphs.impl \
    $$PWD/create_all_direct_neighbour_custom_edges_and_vertices_subgraphs.impl \
    $$PWD/create_all_direct_neighbour_custom_vertices_subgraphs.impl \
    $$PWD/create_all_direct_neighbour_named_edges_and_vertices_subgraphs.impl \
    $$PWD/create_all_direct_neighbour_named_vertices_subgraphs.impl \
    $$PWD/create_all_direct_neighbour_subgraphs.impl \
    $$PWD/create_bundled_edges_and_vertices_k3_graph.impl \
    $$PWD/create_bundled_edges_and_vertices_markov_chain.impl \
    $$PWD/create_bundled_vertices_k2_graph.impl \
    $$PWD/create_bundled_vertices_markov_chain.impl \
    $$PWD/create_custom_and_selectable_edges_and_vertices_k2_graph.impl \
    $$PWD/create_custom_and_selectable_edges_and_vertices_k3_graph.impl \
    $$PWD/create_custom_and_selectable_edges_and_vertices_markov_chain.impl \
    $$PWD/create_custom_and_selectable_edges_and_vertices_path_graph.impl \
    $$PWD/create_custom_and_selectable_edges_and_vertices_petersen_graph.impl \
    $$PWD/create_custom_and_selectable_vertices_k2_graph.impl \
    $$PWD/create_custom_and_selectable_vertices_k3_graph.impl \
    $$PWD/create_custom_and_selectable_vertices_markov_chain.impl \
    $$PWD/create_custom_and_selectable_vertices_path_graph.impl \
    $$PWD/create_custom_and_selectable_vertices_petersen_graph.impl \
    $$PWD/create_custom_edges_and_vertices_k2_graph.impl \
    $$PWD/create_custom_edges_and_vertices_k3_graph.impl \
    $$PWD/create_custom_edges_and_vertices_markov_chain.impl \
    $$PWD/create_custom_edges_and_vertices_path_graph.impl \
    $$PWD/create_custom_edges_and_vertices_petersen_graph.impl \
    $$PWD/create_custom_vertices_k2_graph.impl \
    $$PWD/create_custom_vertices_k3_graph.impl \
    $$PWD/create_custom_vertices_markov_chain.impl \
    $$PWD/create_custom_vertices_path_graph.impl \
    $$PWD/create_custom_vertices_petersen_graph.impl \
    $$PWD/create_direct_neighbour_custom_and_selectable_edges_and_vertices_subgraph.impl \
    $$PWD/create_direct_neighbour_custom_and_selectable_vertices_subgraph.impl \
    $$PWD/create_direct_neighbour_custom_edges_and_vertices_subgraph.impl \
    $$PWD/create_direct_neighbour_custom_vertices_subgraph.impl \
    $$PWD/create_direct_neighbour_named_edges_and_vertices_subgraph.impl \
    $$PWD/create_direct_neighbour_named_vertices_subgraph.impl \
    $$PWD/create_direct_neighbour_subgraph.impl \
    $$PWD/create_direct_neighbour_subgraph_including_in_edges.impl \
    $$PWD/create_empty_directed_bundled_edges_and_vertices_graph.impl \
    $$PWD/create_empty_directed_bundled_vertices_graph.impl \
    $$PWD/create_empty_directed_custom_and_selectable_edges_and_vertices_graph.impl \
    $$PWD/create_empty_directed_custom_and_selectable_vertices_graph.impl \
    $$PWD/create_empty_directed_custom_edges_and_vertices_graph.impl \
    $$PWD/create_empty_directed_custom_vertices_graph.impl \
    $$PWD/create_empty_directed_graph.impl \
    $$PWD/create_empty_directed_graph_with_graph_name.impl \
    $$PWD/create_empty_directed_named_and_selectable_vertices_graph.impl \
    $$PWD/create_empty_directed_named_edges_and_vertices_graph.impl \
    $$PWD/create_empty_directed_named_vertices_graph.impl \
    $$PWD/create_empty_undirected_bundled_edges_and_vertices_graph.impl \
    $$PWD/create_empty_undirected_bundled_vertices_graph.impl \
    $$PWD/create_empty_undirected_custom_and_selectable_edges_and_vertices_graph.impl \
    $$PWD/create_empty_undirected_custom_and_selectable_vertices_graph.impl \
    $$PWD/create_empty_undirected_custom_edges_and_vertices_graph.impl \
    $$PWD/create_empty_undirected_custom_vertices_graph.impl \
    $$PWD/create_empty_undirected_graph.impl \
    $$PWD/create_empty_undirected_graph_with_graph_name.impl \
    $$PWD/create_empty_undirected_named_and_selectable_vertices_graph.impl \
    $$PWD/create_empty_undirected_named_edges_and_vertices_graph.impl \
    $$PWD/create_empty_undirected_named_vertices_graph.impl \
    $$PWD/create_k2_graph.impl \
    $$PWD/create_k2_graph_with_graph_name.impl \
    $$PWD/create_k3_graph.impl \
    $$PWD/create_markov_chain.impl \
    $$PWD/create_markov_chain_with_graph_name.impl \
    $$PWD/create_named_edges_and_vertices_k2_graph.impl \
    $$PWD/create_named_edges_and_vertices_k3_graph.impl \
    $$PWD/create_named_edges_and_vertices_markov_chain.impl \
    $$PWD/create_named_edges_and_vertices_path_graph.impl \
    $$PWD/create_named_edges_and_vertices_petersen_graph.impl \
    $$PWD/create_named_vertices_k2_graph.impl \
    $$PWD/create_named_vertices_k3_graph.impl \
    $$PWD/create_named_vertices_markov_chain.impl \
    $$PWD/create_named_vertices_path_graph.impl \
    $$PWD/create_named_vertices_petersen_graph.impl \
    $$PWD/create_path_graph.impl \
    $$PWD/create_petersen_graph.impl \
    $$PWD/custom_and_selectable_vertices_writer.impl \
    $$PWD/custom_vertex_invariant.impl \
    $$PWD/find_first_bundled_edge_with_my_edge.impl \
    $$PWD/find_first_bundled_vertex_with_my_vertex.impl \
    $$PWD/find_first_custom_edge.impl \
    $$PWD/find_first_custom_edge_with_my_edge.impl \
    $$PWD/find_first_custom_vertex_with_my_vertex.impl \
    $$PWD/find_first_edge_with_name.impl \
    $$PWD/find_first_vertex_with_name.impl \
    $$PWD/formed_reference_to_void.impl \
    $$PWD/get_edge_between_vertices.impl \
    $$PWD/get_edge_descriptors.impl \
    $$PWD/get_edge_iterators.impl \
    $$PWD/get_edge_name.impl \
    $$PWD/get_edge_names.impl \
    $$PWD/get_edge_selectedness.impl \
    $$PWD/get_first_vertex_with_name_out_degree.impl \
    $$PWD/get_graph_name.impl \
    $$PWD/get_my_bundled_edge.impl \
    $$PWD/get_my_bundled_edges.impl \
    $$PWD/get_my_bundled_vertexes.impl \
    $$PWD/get_my_bundled_vertex.impl \
    $$PWD/get_my_bundled_vertexmpl \
    $$PWD/get_my_custom_edge.impl \
    $$PWD/get_my_custom_edges.impl \
    $$PWD/get_my_custom_vertexes.impl \
    $$PWD/get_my_custom_vertex.impl \
    $$PWD/get_n_edges.impl \
    $$PWD/get_n_vertices.impl \
    $$PWD/get_type_name.impl \
    $$PWD/get_vertex_descriptors.impl \
    $$PWD/get_vertex_iterators.impl \
    $$PWD/get_vertex_name.impl \
    $$PWD/get_vertex_names.impl \
    $$PWD/get_vertex_out_degrees.impl \
    $$PWD/get_vertex_selectednesses.impl \
    $$PWD/get_vertex_selectedness.impl \
    $$PWD/graphviz_decode.impl \
    $$PWD/graphviz_encode.impl \
    $$PWD/has_bundled_edge_with_my_edge.impl \
    $$PWD/has_bundled_vertex_with_my_vertex.impl \
    $$PWD/has_custom_edge_with_my_edge.impl \
    $$PWD/has_custom_vertex_with_my_vertex.impl \
    $$PWD/has_edge_between_vertices.impl \
    $$PWD/has_edge_with_name.impl \
    $$PWD/has_vertex_with_name.impl \
    $$PWD/install_edge_custom_type.impl \
    $$PWD/install_edge_is_selected.impl \
    $$PWD/install_vertex_custom_type.impl \
    $$PWD/install_vertex_is_selected.impl \
    $$PWD/is_custom_vertices_isomorphic.impl \
    $$PWD/is_graphviz_friendly.impl \
    $$PWD/is_isomorphic.impl \
    $$PWD/is_named_vertices_isomorphic.impl \
    $$PWD/is_regular_file.impl \
    $$PWD/is_valid_dot_file.impl \
    $$PWD/load_directed_bundled_edges_and_vertices_graph_from_dot.impl \
    $$PWD/load_directed_bundled_vertices_graph_from_dot.impl \
    $$PWD/load_directed_custom_and_selectable_edges_and_vertices_graph_from_dot.impl \
    $$PWD/load_directed_custom_and_selectable_vertices_graph_from_dot.impl \
    $$PWD/load_directed_custom_edges_and_vertices_graph_from_dot.impl \
    $$PWD/load_directed_custom_vertices_graph_from_dot.impl \
    $$PWD/load_directed_graph_from_dot.impl \
    $$PWD/load_directed_graph_with_graph_name_from_dot.impl \
    $$PWD/load_directed_named_edges_and_vertices_graph_from_dot.impl \
    $$PWD/load_directed_named_vertices_graph_from_dot.impl \
    $$PWD/load_undirected_bundled_edges_and_vertices_graph_from_dot.impl \
    $$PWD/load_undirected_bundled_vertices_graph_from_dot.impl \
    $$PWD/load_undirected_custom_and_selectable_edges_and_vertices_graph_from_dot.impl \
    $$PWD/load_undirected_custom_and_selectable_vertices_graph_from_dot.impl \
    $$PWD/load_undirected_custom_edges_and_vertices_graph_from_dot.impl \
    $$PWD/load_undirected_custom_vertices_graph_from_dot.impl \
    $$PWD/load_undirected_graph_from_dot.impl \
    $$PWD/load_undirected_graph_with_graph_name_from_dot.impl \
    $$PWD/load_undirected_named_edges_and_vertices_graph_from_dot.impl \
    $$PWD/load_undirected_named_vertices_graph_from_dot.impl \
    $$PWD/make_bundled_edges_writer.impl \
    $$PWD/make_bundled_vertices_writer.impl \
    $$PWD/make_custom_and_selectable_vertices_writer.impl \
    $$PWD/my_bundled_edge.impl \
    $$PWD/my_bundled_vertex.impl \
    $$PWD/my_custom_edge.impl \
    $$PWD/my_custom_vertex.impl \
    $$PWD/named_vertex_invariant.impl \
    $$PWD/no_matching_function_for_call_to_clear_out_edges.impl \
    $$PWD/property_not_found_node_id.impl \
    $$PWD/remove_edge_between_vertices_with_names.impl \
    $$PWD/remove_first_edge_with_name.impl \
    $$PWD/remove_first_vertex_with_name.impl \
    $$PWD/remove_selected_custom_edges.impl \
    $$PWD/remove_selected_custom_edges_and_vertices.impl \
    $$PWD/remove_selected_custom_vertices.impl \
    $$PWD/remove_nth_vertex.impl \
    $$PWD/save_bundled_edges_and_vertices_graph_to_dot.impl \
    $$PWD/save_bundled_vertices_graph_to_dot.impl \
    $$PWD/save_custom_and_selectable_edges_and_vertices_graph_to_dot.impl \
    $$PWD/save_custom_and_selectable_vertices_graph_to_dot.impl \
    $$PWD/save_custom_edges_and_vertices_graph_to_dot.impl \
    $$PWD/save_custom_vertices_graph_to_dot.impl \
    $$PWD/save_custom_vertices_graph_to_dot.impl \
    $$PWD/save_graph_to_dot.impl \
    $$PWD/save_graph_with_graph_name_to_dot.impl \
    $$PWD/save_named_edges_and_vertices_graph_to_dot.impl \
    $$PWD/save_named_edges_and_vertices_graph_to_dot.impl \
    $$PWD/save_named_vertices_graph_to_dot.impl \
    $$PWD/save_named_vertices_graph_to_dot_using_lambda.impl \
    $$PWD/set_edge_name.impl \
    $$PWD/set_edge_selectedness.impl \
    $$PWD/set_graph_name.impl \
    $$PWD/set_my_bundled_edge.impl \
    $$PWD/set_my_bundled_vertexes.impl \
    $$PWD/set_my_bundled_vertex.impl \
    $$PWD/set_my_custom_edge.impl \
    $$PWD/set_my_custom_vertexes.impl \
    $$PWD/set_my_custom_vertex.impl \
    $$PWD/set_vertex_name.impl \
    $$PWD/set_vertex_names.impl \
    $$PWD/set_vertex_selectedness.impl \
    $$PWD/add_edge_between_custom_vertices.impl \
    $$PWD/has_vertex_with_my_vertex.impl \
    $$PWD/select_random_vertex.impl \
    $$PWD/has_custom_edge_with_my_edge_f.impl \
    $$PWD/find_first_custom_edge_with_my_edge_f.impl
