#ifndef BUNDLED_EDGES_WRITER_H
#define BUNDLED_EDGES_WRITER_H

#ifndef BOOST_GRAPH_TUTORIAL_NO_GRAPHVIZ

#include "bundled_edges_writer.impl"

#endif //BOOST_GRAPH_TUTORIAL_NO_GRAPHVIZ

#endif // BUNDLED_EDGES_WRITER_H
