#ifndef COUNT_UNDIRECTED_GRAPH_CONNECTED_COMPONENTS_H
#define COUNT_UNDIRECTED_GRAPH_CONNECTED_COMPONENTS_H

#include "count_undirected_graph_connected_components.impl"

void count_undirected_graph_connected_components_test() noexcept;

#endif // COUNT_UNDIRECTED_GRAPH_CONNECTED_COMPONENTS_H
