#ifndef CREATE_EMPTY_UNDIRECTED_NAMED_VERTICES_GRAPH_H
#define CREATE_EMPTY_UNDIRECTED_NAMED_VERTICES_GRAPH_H

#include "create_empty_undirected_named_vertices_graph.impl"

void create_empty_undirected_named_vertices_graph_test() noexcept;

#endif // CREATE_EMPTY_UNDIRECTED_NAMED_VERTICES_GRAPH_H
