#ifndef CREATE_EMPTY_UNDIRECTED_CUSTOM_AND_SELECTABLE_VERTICES_GRAPH_H
#define CREATE_EMPTY_UNDIRECTED_CUSTOM_AND_SELECTABLE_VERTICES_GRAPH_H

#include "create_empty_undirected_custom_and_selectable_vertices_graph.impl"

void create_empty_undirected_custom_and_selectable_vertices_graph_test() noexcept;

#endif // CREATE_EMPTY_UNDIRECTED_CUSTOM_AND_SELECTABLE_VERTICES_GRAPH_H
