#ifndef CREATE_EMPTY_DIRECTED_NAMED_AND_SELECTABLE_VERTICES_GRAPH_H
#define CREATE_EMPTY_DIRECTED_NAMED_AND_SELECTABLE_VERTICES_GRAPH_H

#include "create_empty_directed_named_and_selectable_vertices_graph.impl"

void create_empty_directed_named_and_selectable_vertices_graph_test() noexcept;

#endif // CREATE_EMPTY_DIRECTED_NAMED_AND_SELECTABLE_VERTICES_GRAPH_H
