#ifndef CREATE_ALL_DIRECT_NEIGHBOUR_NAMED_EDGES_AND_VERTICES_SUBGRAPHS_H
#define CREATE_ALL_DIRECT_NEIGHBOUR_NAMED_EDGES_AND_VERTICES_SUBGRAPHS_H

#include "create_all_direct_neighbour_named_edges_and_vertices_subgraphs.impl"

void create_all_direct_neighbour_named_edges_and_vertices_subgraphs_test() noexcept;

#endif // CREATE_ALL_DIRECT_NEIGHBOUR_NAMED_EDGES_AND_VERTICES_SUBGRAPHS_H
