#ifndef CREATE_DIRECT_NEIGHBOUR_NAMED_VERTICES_SUBGRAPH_H
#define CREATE_DIRECT_NEIGHBOUR_NAMED_VERTICES_SUBGRAPH_H

#include "create_direct_neighbour_named_vertices_subgraph.impl"

void create_direct_neighbour_named_vertices_subgraph_test() noexcept;

#endif // CREATE_DIRECT_NEIGHBOUR_NAMED_VERTICES_SUBGRAPH_H
