#ifndef FIND_FIRST_CUSTOM_VERTEX_WITH_MY_VERTEX_H
#define FIND_FIRST_CUSTOM_VERTEX_WITH_MY_VERTEX_H

#include "find_first_custom_vertex_with_my_vertex.impl"

#endif // FIND_FIRST_CUSTOM_VERTEX_WITH_MY_VERTEX_H
