#ifndef FIND_FIRST_BUNDLED_VERTEX_WITH_MY_VERTEX_H
#define FIND_FIRST_BUNDLED_VERTEX_WITH_MY_VERTEX_H

#include "find_first_bundled_vertex_with_my_vertex.impl"

void find_first_bundled_vertex_with_my_vertex_test() noexcept;

#endif // FIND_FIRST_BUNDLED_VERTEX_WITH_MY_VERTEX_H
