#ifndef GET_FIRST_VERTEX_WITH_NAME_OUT_DEGREE_H
#define GET_FIRST_VERTEX_WITH_NAME_OUT_DEGREE_H

#include "get_first_vertex_with_name_out_degree.impl"

#endif // GET_FIRST_VERTEX_WITH_NAME_OUT_DEGREE_H
