#include "load_undirected_custom_edges_and_vertices_graph_from_dot.h"
#ifndef BOOST_GRAPH_TUTORIAL_NO_GRAPHVIZ
#include "load_undirected_custom_edges_and_vertices_graph_from_dot.impl"
#endif //BOOST_GRAPH_TUTORIAL_NO_GRAPHVIZ
