#include "load_undirected_named_edges_and_vertices_graph_from_dot.h"

#ifndef BOOST_GRAPH_TUTORIAL_NO_GRAPHVIZ
#include "load_undirected_named_edges_and_vertices_graph_from_dot.impl"
#endif //BOOST_GRAPH_TUTORIAL_NO_GRAPHVIZ
