#ifndef MAKE_CUSTOM_AND_SELECTABLE_VERTICES_WRITER_H
#define MAKE_CUSTOM_AND_SELECTABLE_VERTICES_WRITER_H

#include "custom_and_selectable_vertices_writer.h"

#include "make_custom_and_selectable_vertices_writer.impl"

#endif // MAKE_CUSTOM_AND_SELECTABLE_VERTICES_WRITER_H
