#ifndef SAVE_CUSTOM_AND_SELECTABLE_VERTICES_GRAPH_TO_DOT_H
#define SAVE_CUSTOM_AND_SELECTABLE_VERTICES_GRAPH_TO_DOT_H

#include "save_custom_and_selectable_vertices_graph_to_dot.impl"

void save_custom_and_selectable_vertices_graph_to_dot_test() noexcept;

#endif // SAVE_CUSTOM_AND_SELECTABLE_VERTICES_GRAPH_TO_DOT_H
