#ifndef SAVE_CUSTOM_AND_SELECTABLE_VERTICES_GRAPH_TO_DOT_H
#define SAVE_CUSTOM_AND_SELECTABLE_VERTICES_GRAPH_TO_DOT_H

#ifndef BOOST_GRAPH_TUTORIAL_NO_GRAPHVIZ
#include "save_custom_and_selectable_vertices_graph_to_dot.impl"
#else
#error(Do not include this file when BOOST_GRAPH_TUTORIAL_NO_GRAPHVIZ is defined)
#endif // BOOST_GRAPH_TUTORIAL_NO_GRAPHVIZ

#endif // SAVE_CUSTOM_AND_SELECTABLE_VERTICES_GRAPH_TO_DOT_H
