#ifndef SAVE_BUNDLED_VERTICES_GRAPH_TO_DOT_H
#define SAVE_BUNDLED_VERTICES_GRAPH_TO_DOT_H

#ifndef BOOST_GRAPH_TUTORIAL_NO_GRAPHVIZ
#include "save_bundled_vertices_graph_to_dot.impl"
#endif // BOOST_GRAPH_TUTORIAL_NO_GRAPHVIZ

#endif // SAVE_BUNDLED_VERTICES_GRAPH_TO_DOT_H
