#ifndef SAVE_BUNDLED_EDGES_AND_VERTICES_GRAPH_TO_DOT_H
#define SAVE_BUNDLED_EDGES_AND_VERTICES_GRAPH_TO_DOT_H

#include "save_bundled_edges_and_vertices_graph_to_dot.impl"

#endif // SAVE_BUNDLED_EDGES_AND_VERTICES_GRAPH_TO_DOT_H
