#ifndef SAVE_NAMED_EDGES_AND_VERTICES_GRAPH_TO_DOT_TEST_H
#define SAVE_NAMED_EDGES_AND_VERTICES_GRAPH_TO_DOT_TEST_H

void save_named_edges_and_vertices_graph_to_dot_test() noexcept;

#endif // SAVE_NAMED_EDGES_AND_VERTICES_GRAPH_TO_DOT_TEST_H
