SOURCES += \
    $$PWD/add_bundled_edge_between_vertices_test.cpp \
    $$PWD/add_bundled_edge_test.cpp \
    $$PWD/add_bundled_vertex_test.cpp \
    $$PWD/add_custom_and_selectable_edge_between_vertices_test.cpp \
    $$PWD/add_custom_and_selectable_edge_test.cpp \
    $$PWD/add_custom_and_selectable_vertex_test.cpp \
    $$PWD/add_custom_edge_between_vertices_test.cpp \
    $$PWD/add_custom_edge_test.cpp \
    $$PWD/add_custom_vertex_test.cpp \
    $$PWD/add_edge_between_custom_vertices_test.cpp \
    $$PWD/add_edge_between_named_vertices_test.cpp \
    $$PWD/add_edge_between_selected_vertices_test.cpp \
    $$PWD/add_edge_between_text_vertices_test.cpp \
    $$PWD/add_edge_test.cpp \
    $$PWD/add_named_and_selectable_vertex_test.cpp \
    $$PWD/add_named_edge_between_vertices_test.cpp \
    $$PWD/add_named_edge_test.cpp \
    $$PWD/add_named_vertex_test.cpp \
    $$PWD/add_text_edge_between_vertices_test.cpp \
    $$PWD/add_text_edge_test.cpp \
    $$PWD/add_text_vertex_test.cpp \
    $$PWD/add_vertex_test.cpp \
    $$PWD/clear_first_vertex_with_name_test.cpp \
    $$PWD/clear_first_vertex_with_text_test.cpp \
    $$PWD/convert_svg_to_png_test.cpp \
    $$PWD/copy_file_test.cpp \
    $$PWD/count_directed_graph_connected_components_test.cpp \
    $$PWD/count_edges_with_selectedness_test.cpp \
    $$PWD/count_max_number_of_pieces_test.cpp \
    $$PWD/count_undirected_graph_connected_components_test.cpp \
    $$PWD/count_undirected_graph_levels_test.cpp \
    $$PWD/count_vertices_with_name_test.cpp \
    $$PWD/count_vertices_with_selectedness_test.cpp \
    $$PWD/count_vertices_with_text_test.cpp \
    $$PWD/create_all_direct_neighbour_bundled_edges_and_vertices_subgraphs_test.cpp \
    $$PWD/create_all_direct_neighbour_named_edges_and_vertices_subgraphs_test.cpp \
    $$PWD/create_all_direct_neighbour_subgraphs_test.cpp \
    $$PWD/create_all_direct_neighbour_text_edges_and_vertices_subgraphs_test.cpp \
    $$PWD/create_bundled_edges_and_vertices_k2_graph_test.cpp \
    $$PWD/create_bundled_edges_and_vertices_markov_chain_test.cpp \
    $$PWD/create_bundled_edges_and_vertices_path_graph_test.cpp \
    $$PWD/create_bundled_edges_and_vertices_petersen_graph_test.cpp \
    $$PWD/create_bundled_vertices_markov_chain_test.cpp \
    $$PWD/create_custom_and_selectable_edges_and_vertices_markov_chain_test.cpp \
    $$PWD/create_custom_and_selectable_edges_and_vertices_petersen_graph_test.cpp \
    $$PWD/create_custom_and_selectable_vertices_markov_chain_test.cpp \
    $$PWD/create_custom_and_selectable_vertices_petersen_graph_test.cpp \
    $$PWD/create_custom_edges_and_vertices_markov_chain_test.cpp \
    $$PWD/create_custom_edges_and_vertices_petersen_graph_test.cpp \
    $$PWD/create_custom_vertices_markov_chain_test.cpp \
    $$PWD/create_custom_vertices_petersen_graph_test.cpp \
    $$PWD/create_direct_neighbour_bundled_edges_and_vertices_subgraph_test.cpp \
    $$PWD/create_direct_neighbour_custom_and_selectable_edges_and_vertices_subgraph_test.cpp \
    $$PWD/create_direct_neighbour_custom_and_selectable_vertices_subgraph_test.cpp \
    $$PWD/create_direct_neighbour_custom_edges_and_vertices_subgraph_test.cpp \
    $$PWD/create_direct_neighbour_custom_vertices_subgraph_test.cpp \
    $$PWD/create_direct_neighbour_named_edges_and_vertices_subgraph_test.cpp \
    $$PWD/create_direct_neighbour_named_vertices_subgraph_test.cpp \
    $$PWD/create_direct_neighbour_subgraph_including_in_edges_test.cpp \
    $$PWD/create_direct_neighbour_subgraph_test.cpp \
    $$PWD/create_direct_neighbour_text_edges_and_vertices_subgraph_test.cpp \
    $$PWD/create_direct_neighbour_text_vertices_subgraph_test.cpp \
    $$PWD/create_empty_directed_bundled_edges_and_vertices_graph_test.cpp \
    $$PWD/create_empty_directed_bundled_vertices_graph_test.cpp \
    $$PWD/create_empty_directed_custom_and_selectable_edges_and_vertices_graph_test.cpp \
    $$PWD/create_empty_directed_custom_and_selectable_vertices_graph_test.cpp \
    $$PWD/create_empty_directed_custom_edges_and_vertices_graph_test.cpp \
    $$PWD/create_empty_directed_custom_vertices_graph_test.cpp \
    $$PWD/create_empty_directed_graph_test.cpp \
    $$PWD/create_empty_directed_graph_with_graph_name_test.cpp \
    $$PWD/create_empty_directed_named_and_selectable_vertices_graph_test.cpp \
    $$PWD/create_empty_directed_named_edges_and_vertices_graph_test.cpp \
    $$PWD/create_empty_directed_named_vertices_graph_test.cpp \
    $$PWD/create_empty_directed_text_edges_and_vertices_graph_test.cpp \
    $$PWD/create_empty_directed_text_vertices_graph_test.cpp \
    $$PWD/create_empty_undirected_bundled_edges_and_vertices_graph_test.cpp \
    $$PWD/create_empty_undirected_bundled_vertices_graph_test.cpp \
    $$PWD/create_empty_undirected_custom_and_selectable_edges_and_vertices_graph_test.cpp \
    $$PWD/create_empty_undirected_custom_and_selectable_vertices_graph_test.cpp \
    $$PWD/create_empty_undirected_custom_edges_and_vertices_graph_test.cpp \
    $$PWD/create_empty_undirected_custom_vertices_graph_test.cpp \
    $$PWD/create_empty_undirected_graph_test.cpp \
    $$PWD/create_empty_undirected_graph_with_graph_name_test.cpp \
    $$PWD/create_empty_undirected_named_and_selectable_vertices_graph_test.cpp \
    $$PWD/create_empty_undirected_named_edges_and_vertices_graph_test.cpp \
    $$PWD/create_empty_undirected_named_vertices_graph_test.cpp \
    $$PWD/create_empty_undirected_text_edges_and_vertices_graph_test.cpp \
    $$PWD/create_empty_undirected_text_vertices_graph_test.cpp \
    $$PWD/create_k2_graph_with_graph_name_test.cpp \
    $$PWD/create_markov_chain_with_graph_name_test.cpp \
    $$PWD/create_named_edges_and_vertices_markov_chain_test.cpp \
    $$PWD/create_named_vertices_markov_chain_test.cpp \
    $$PWD/create_named_vertices_petersen_graph_test.cpp \
    $$PWD/create_nasty_directed_bundled_vertices_graph_test.cpp \
    $$PWD/create_nasty_directed_custom_and_selectable_edges_and_vertices_graph_test.cpp \
    $$PWD/create_nasty_directed_custom_and_selectable_vertices_graph_test.cpp \
    $$PWD/create_nasty_directed_custom_edges_and_vertices_graph_test.cpp \
    $$PWD/create_nasty_directed_custom_vertices_graph_test.cpp \
    $$PWD/create_nasty_directed_named_vertices_graph_test.cpp \
    $$PWD/create_nasty_directed_text_vertices_graph_test.cpp \
    $$PWD/create_nasty_undirected_custom_and_selectable_vertices_graph_test.cpp \
    $$PWD/create_nasty_undirected_custom_edges_and_vertices_graph_test.cpp \
    $$PWD/create_text_edges_and_vertices_markov_chain_test.cpp \
    $$PWD/create_text_vertices_markov_chain_test.cpp \
    $$PWD/create_text_vertices_petersen_graph_test.cpp \
    $$PWD/create_tutorial_chapters_graph_test.cpp \
    $$PWD/create_tutorial_subchapters_graph_test.cpp \
    $$PWD/custom_and_selectable_vertices_writer_test.cpp \
    $$PWD/file_to_vector_test.cpp \
    $$PWD/find_first_bundled_edge_with_my_edge_test.cpp \
    $$PWD/find_first_bundled_vertex_with_my_vertex_test.cpp \
    $$PWD/find_first_custom_edge_test.cpp \
    $$PWD/find_first_custom_edge_with_my_edge_test.cpp \
    $$PWD/find_first_custom_vertex_test.cpp \
    $$PWD/find_first_custom_vertex_with_my_vertex_test.cpp \
    $$PWD/find_first_edge_with_name_test.cpp \
    $$PWD/find_first_edge_with_text_test.cpp \
    $$PWD/find_first_vertex_with_name_test.cpp \
    $$PWD/find_first_vertex_with_text_test.cpp \
    $$PWD/formed_reference_to_void_test.cpp \
    $$PWD/get_bits_test.cpp \
    $$PWD/get_edge_between_vertices_test.cpp \
    $$PWD/get_edge_descriptors_test.cpp \
    $$PWD/get_edge_iterators_test.cpp \
    $$PWD/get_edge_name_test.cpp \
    $$PWD/get_edge_names_test.cpp \
    $$PWD/get_edge_selectedness_test.cpp \
    $$PWD/get_edge_text_test.cpp \
    $$PWD/get_edge_texts_test.cpp \
    $$PWD/get_edges_test.cpp \
    $$PWD/get_first_vertex_with_name_out_degree_test.cpp \
    $$PWD/get_first_vertex_with_text_out_degree_test.cpp \
    $$PWD/get_graph_name_test.cpp \
    $$PWD/get_graph_text_test.cpp \
    $$PWD/get_my_bundled_edge_test.cpp \
    $$PWD/get_my_bundled_edges_test.cpp \
    $$PWD/get_my_bundled_vertex_test.cpp \
    $$PWD/get_my_bundled_vertexes_test.cpp \
    $$PWD/get_my_custom_edge_test.cpp \
    $$PWD/get_my_custom_edges_test.cpp \
    $$PWD/get_my_custom_vertex_test.cpp \
    $$PWD/get_my_custom_vertexes_test.cpp \
    $$PWD/get_n_edges_test.cpp \
    $$PWD/get_n_vertices_test.cpp \
    $$PWD/get_sorted_bundled_edge_my_edges_test.cpp \
    $$PWD/get_sorted_bundled_vertex_my_vertexes_test.cpp \
    $$PWD/get_sorted_custom_edge_my_edges_test.cpp \
    $$PWD/get_sorted_custom_vertex_my_vertexes_test.cpp \
    $$PWD/get_sorted_named_vertex_my_vertexes_test.cpp \
    $$PWD/get_sorted_text_vertex_my_vertexes_test.cpp \
    $$PWD/get_sorted_vertex_names_test.cpp \
    $$PWD/get_sorted_vertex_selectednesses_test.cpp \
    $$PWD/get_sorted_vertex_texts_test.cpp \
    $$PWD/get_type_name_test.cpp \
    $$PWD/get_type_text_test.cpp \
    $$PWD/get_vertex_descriptors_test.cpp \
    $$PWD/get_vertex_iterators_test.cpp \
    $$PWD/get_vertex_name_test.cpp \
    $$PWD/get_vertex_names_test.cpp \
    $$PWD/get_vertex_out_degrees_test.cpp \
    $$PWD/get_vertex_selectedness_test.cpp \
    $$PWD/get_vertex_selectednesses_test.cpp \
    $$PWD/get_vertex_text_test.cpp \
    $$PWD/get_vertex_texts_test.cpp \
    $$PWD/get_vertices_with_selectedness_test.cpp \
    $$PWD/graphviz_decode_test.cpp \
    $$PWD/graphviz_encode_test.cpp \
    $$PWD/has_bundled_edge_with_my_edge_test.cpp \
    $$PWD/has_bundled_vertex_with_my_vertex_test.cpp \
    $$PWD/has_custom_edge_test.cpp \
    $$PWD/has_custom_edge_with_my_edge_test.cpp \
    $$PWD/has_custom_vertex_test.cpp \
    $$PWD/has_custom_vertex_with_my_vertex_test.cpp \
    $$PWD/has_dot_test.cpp \
    $$PWD/has_edge_between_vertices_test.cpp \
    $$PWD/has_edge_with_name_test.cpp \
    $$PWD/has_edge_with_text_test.cpp \
    $$PWD/has_vertex_with_name_test.cpp \
    $$PWD/has_vertex_with_text_test.cpp \
    $$PWD/install_edge_is_selected_test.cpp \
    $$PWD/is_custom_vertices_isomorphic_test.cpp \
    $$PWD/is_graphviz_friendly_test.cpp \
    $$PWD/is_isomorphic_test.cpp \
    $$PWD/is_named_vertices_isomorphic_test.cpp \
    $$PWD/is_regular_file_test.cpp \
    $$PWD/is_text_vertices_isomorphic_test.cpp \
    $$PWD/make_bundled_vertices_writer_test.cpp \
    $$PWD/make_custom_and_selectable_vertices_writer_test.cpp \
    $$PWD/my_bundled_edge_test.cpp \
    $$PWD/my_bundled_vertex_test.cpp \
    $$PWD/my_custom_edge_test.cpp \
    $$PWD/my_custom_vertex_test.cpp \
    $$PWD/no_matching_function_for_call_to_clear_out_edges_test.cpp \
    $$PWD/remove_edge_between_vertices_with_names_test.cpp \
    $$PWD/remove_edge_between_vertices_with_texts_test.cpp \
    $$PWD/remove_first_edge_with_name_test.cpp \
    $$PWD/remove_first_edge_with_text_test.cpp \
    $$PWD/remove_first_vertex_with_name_test.cpp \
    $$PWD/remove_first_vertex_with_text_test.cpp \
    $$PWD/remove_nth_vertex_test.cpp \
    $$PWD/remove_selected_custom_edges_and_vertices_test.cpp \
    $$PWD/remove_selected_custom_edges_test.cpp \
    $$PWD/remove_selected_custom_vertices_test.cpp \
    $$PWD/remove_self_loops_test.cpp \
    $$PWD/remove_vertex_if_test.cpp \
    $$PWD/select_random_vertex_test.cpp \
    $$PWD/seperate_string_test.cpp \
    $$PWD/set_edge_name_test.cpp \
    $$PWD/set_edge_selectedness_test.cpp \
    $$PWD/set_edge_text_test.cpp \
    $$PWD/set_graph_name_test.cpp \
    $$PWD/set_graph_text_test.cpp \
    $$PWD/set_my_bundled_edge_test.cpp \
    $$PWD/set_my_bundled_vertex_test.cpp \
    $$PWD/set_my_bundled_vertexes_test.cpp \
    $$PWD/set_my_custom_edge_test.cpp \
    $$PWD/set_my_custom_vertex_test.cpp \
    $$PWD/set_my_custom_vertexes_test.cpp \
    $$PWD/set_vertex_name_test.cpp \
    $$PWD/set_vertex_names_test.cpp \
    $$PWD/set_vertex_selectedness_test.cpp \
    $$PWD/set_vertex_text_test.cpp \
    $$PWD/set_vertex_texts_test.cpp \
    $$PWD/show_dot_test.cpp

OTHER_FILES += \
    $$PWD/add_bundled_edge_between_vertices_demo.impl \
    $$PWD/add_bundled_edge_demo.impl \
    $$PWD/add_bundled_vertex_demo.impl \
    $$PWD/add_custom_and_selectable_edge_between_vertices_demo.impl \
    $$PWD/add_custom_and_selectable_edge_demo.impl \
    $$PWD/add_custom_and_selectable_vertex_demo.impl \
    $$PWD/add_custom_edge_between_vertices_demo.impl \
    $$PWD/add_custom_edge_demo.impl \
    $$PWD/add_custom_vertex_demo.impl \
    $$PWD/add_edge_between_custom_vertices_demo.impl \
    $$PWD/add_edge_between_named_vertices_demo.impl \
    $$PWD/add_edge_between_selected_vertices_demo.impl \
    $$PWD/add_edge_between_text_vertices_demo.impl \
    $$PWD/add_edge_demo.impl \
    $$PWD/add_named_and_selectable_vertex_demo.impl \
    $$PWD/add_named_edge_between_vertices_demo.impl \
    $$PWD/add_named_edge_demo.impl \
    $$PWD/add_named_vertex_demo.impl \
    $$PWD/add_text_edge_between_vertices_demo.impl \
    $$PWD/add_text_edge_demo.impl \
    $$PWD/add_text_vertex_demo.impl \
    $$PWD/add_vertex_demo.impl \
    $$PWD/clear_first_vertex_with_name_demo.impl \
    $$PWD/clear_first_vertex_with_text_demo.impl \
    $$PWD/count_directed_graph_connected_components_demo.impl \
    $$PWD/count_edges_with_selectedness_demo.impl \
    $$PWD/count_undirected_graph_connected_components_demo.impl \
    $$PWD/count_undirected_graph_levels_demo.impl \
    $$PWD/count_vertices_with_name_demo.impl \
    $$PWD/count_vertices_with_selectedness_demo.impl \
    $$PWD/count_vertices_with_text_demo.impl \
    $$PWD/create_all_direct_neighbour_bundled_edges_and_vertices_subgraphs_test.cpp \
    $$PWD/create_all_direct_neighbour_custom_and_selectable_edges_and_vertices_subgraphs_demo.impl \
    $$PWD/create_all_direct_neighbour_custom_and_selectable_vertices_subgraphs_demo.impl \
    $$PWD/create_all_direct_neighbour_custom_edges_and_vertices_subgraphs_demo.impl \
    $$PWD/create_all_direct_neighbour_custom_vertices_subgraphs_demo.impl \
    $$PWD/create_all_direct_neighbour_named_edges_and_vertices_subgraphs_demo.impl \
    $$PWD/create_all_direct_neighbour_named_vertices_subgraphs_demo.impl \
    $$PWD/create_all_direct_neighbour_subgraphs_demo.impl \
    $$PWD/create_all_direct_neighbour_text_edges_and_vertices_subgraphs_demo.impl \
    $$PWD/create_all_direct_neighbour_text_vertices_subgraphs_demo.impl \
    $$PWD/create_bundled_edges_and_vertices_k2_graph_demo.impl \
    $$PWD/create_bundled_edges_and_vertices_k3_graph_demo.impl \
    $$PWD/create_bundled_edges_and_vertices_markov_chain_demo.impl \
    $$PWD/create_bundled_edges_and_vertices_path_demo.impl \
    $$PWD/create_bundled_edges_and_vertices_petersen_demo.impl \
    $$PWD/create_bundled_vertices_k2_graph_demo.impl \
    $$PWD/create_bundled_vertices_markov_chain_demo.impl \
    $$PWD/create_custom_and_selectable_edges_and_vertices_k2_graph_demo.impl \
    $$PWD/create_custom_and_selectable_edges_and_vertices_k3_graph_demo.impl \
    $$PWD/create_custom_and_selectable_edges_and_vertices_markov_chain_demo.impl \
    $$PWD/create_custom_and_selectable_edges_and_vertices_path_graph_demo.impl \
    $$PWD/create_custom_and_selectable_edges_and_vertices_petersen_graph_demo.impl \
    $$PWD/create_custom_and_selectable_vertices_k2_graph_demo.impl \
    $$PWD/create_custom_and_selectable_vertices_k3_graph_demo.impl \
    $$PWD/create_custom_and_selectable_vertices_markov_chain_demo.impl \
    $$PWD/create_custom_and_selectable_vertices_path_graph_demo.impl \
    $$PWD/create_custom_and_selectable_vertices_petersen_graph_demo.impl \
    $$PWD/create_custom_edges_and_vertices_k2_graph_demo.impl \
    $$PWD/create_custom_edges_and_vertices_k3_graph_demo.impl \
    $$PWD/create_custom_edges_and_vertices_markov_chain_demo.impl \
    $$PWD/create_custom_edges_and_vertices_path_graph_demo.impl \
    $$PWD/create_custom_edges_and_vertices_petersen_graph_demo.impl \
    $$PWD/create_custom_vertices_k2_graph_demo.impl \
    $$PWD/create_custom_vertices_k3_graph_demo.impl \
    $$PWD/create_custom_vertices_markov_chain_demo.impl \
    $$PWD/create_custom_vertices_path_graph_demo.impl \
    $$PWD/create_custom_vertices_petersen_graph_demo.impl \
    $$PWD/create_direct_neighbour_bundled_edges_and_vertices_subgraph_demo.impl \
    $$PWD/create_direct_neighbour_custom_and_selectable_edges_and_vertices_subgraph_demo.impl \
    $$PWD/create_direct_neighbour_custom_and_selectable_vertices_subgraph_demo.impl \
    $$PWD/create_direct_neighbour_custom_edges_and_vertices_subgraph_demo.impl \
    $$PWD/create_direct_neighbour_custom_vertices_subgraph_demo.impl \
    $$PWD/create_direct_neighbour_named_edges_and_vertices_subgraph_demo.impl \
    $$PWD/create_direct_neighbour_named_vertices_subgraph_demo.impl \
    $$PWD/create_direct_neighbour_subgraph_demo.impl \
    $$PWD/create_direct_neighbour_subgraph_including_in_edges_demo.impl \
    $$PWD/create_direct_neighbour_text_edges_and_vertices_subgraph_demo.impl \
    $$PWD/create_direct_neighbour_text_vertices_subgraph_demo.impl \
    $$PWD/create_empty_directed_bundled_edges_and_vertices_graph_demo.impl \
    $$PWD/create_empty_directed_custom_and_selectable_edges_and_vertices_graph_demo.impl \
    $$PWD/create_empty_directed_custom_and_selectable_vertices_graph_demo.impl \
    $$PWD/create_empty_directed_custom_edges_and_vertices_graph_demo.impl \
    $$PWD/create_empty_directed_custom_vertices_graph_demo.impl \
    $$PWD/create_empty_directed_graph_demo.impl \
    $$PWD/create_empty_directed_graph_with_graph_name_demo.impl \
    $$PWD/create_empty_directed_named_and_selectable_vertices_graph_demo.impl \
    $$PWD/create_empty_directed_named_edges_and_vertices_graph_demo.impl \
    $$PWD/create_empty_directed_named_vertices_graph_demo.impl \
    $$PWD/create_empty_directed_text_edges_and_vertices_graph_demo.impl \
    $$PWD/create_empty_directed_text_vertices_graph_demo.impl \
    $$PWD/create_empty_undirected_bundled_edges_and_vertices_graph_demo.impl \
    $$PWD/create_empty_undirected_custom_and_selectable_edges_and_vertices_graph_demo.impl \
    $$PWD/create_empty_undirected_custom_and_selectable_vertices_graph_demo.impl \
    $$PWD/create_empty_undirected_custom_edges_and_vertices_graph_demo.impl \
    $$PWD/create_empty_undirected_custom_vertices_graph_demo.impl \
    $$PWD/create_empty_undirected_graph_demo.impl \
    $$PWD/create_empty_undirected_graph_with_graph_name_demo.impl \
    $$PWD/create_empty_undirected_named_and_selectable_vertices_graph_demo.impl \
    $$PWD/create_empty_undirected_named_edges_and_vertices_graph_demo.impl \
    $$PWD/create_empty_undirected_named_vertices_graph_demo.impl \
    $$PWD/create_empty_undirected_text_edges_and_vertices_graph_demo.impl \
    $$PWD/create_empty_undirected_text_vertices_graph_demo.impl \
    $$PWD/create_k2_graph_demo.impl \
    $$PWD/create_k2_graph_with_graph_name_demo.impl \
    $$PWD/create_k3_graph_demo.impl \
    $$PWD/create_markov_chain_demo.impl \
    $$PWD/create_markov_chain_with_graph_name_demo.impl \
    $$PWD/create_named_edges_and_vertices_k2_graph_demo.impl \
    $$PWD/create_named_edges_and_vertices_k3_graph_demo.impl \
    $$PWD/create_named_edges_and_vertices_markov_chain_demo.impl \
    $$PWD/create_named_edges_and_vertices_path_graph_demo.impl \
    $$PWD/create_named_edges_and_vertices_petersen_graph_demo.impl \
    $$PWD/create_named_vertices_k2_graph_demo.impl \
    $$PWD/create_named_vertices_k3_graph_demo.impl \
    $$PWD/create_named_vertices_markov_chain_demo.impl \
    $$PWD/create_named_vertices_path_graph_demo.impl \
    $$PWD/create_named_vertices_petersen_graph_demo.impl \
    $$PWD/create_path_graph_demo.impl \
    $$PWD/create_petersen_graph_demo.impl \
    $$PWD/create_text_edges_and_vertices_k2_graph_demo.impl \
    $$PWD/create_text_edges_and_vertices_k3_graph_demo.impl \
    $$PWD/create_text_edges_and_vertices_markov_chain_demo.impl \
    $$PWD/create_text_edges_and_vertices_path_graph_demo.impl \
    $$PWD/create_text_edges_and_vertices_petersen_graph_demo.impl \
    $$PWD/create_text_vertices_k2_graph_demo.impl \
    $$PWD/create_text_vertices_k3_graph_demo.impl \
    $$PWD/create_text_vertices_markov_chain_demo.impl \
    $$PWD/create_text_vertices_path_graph_demo.impl \
    $$PWD/create_text_vertices_petersen_graph_demo.impl \
    $$PWD/find_first_bundled_edge_with_my_edge_demo.impl \
    $$PWD/find_first_bundled_vertex_with_my_vertex_demo.impl \
    $$PWD/find_first_custom_edge.impl \
    $$PWD/find_first_custom_edge_with_my_edge_demo.impl \
    $$PWD/find_first_custom_vertex_demo.impl \
    $$PWD/find_first_custom_vertex_with_my_vertex_demo.impl \
    $$PWD/find_first_edge_with_name_demo.impl \
    $$PWD/find_first_edge_with_text_demo.impl \
    $$PWD/find_first_vertex_with_name_demo.impl \
    $$PWD/find_first_vertex_with_text_demo.impl \
    $$PWD/get_edge_between_vertices_demo.impl \
    $$PWD/get_edge_descriptors_demo.impl \
    $$PWD/get_edge_iterators_demo.impl \
    $$PWD/get_edge_name_demo.impl \
    $$PWD/get_edge_names_demo.impl \
    $$PWD/get_edge_selectedness_demo.impl \
    $$PWD/get_edge_text_demo.impl \
    $$PWD/get_edge_texts_demo.impl \
    $$PWD/get_first_vertex_with_name_out_degree_demo.impl \
    $$PWD/get_first_vertex_with_text_out_degree_demo.impl \
    $$PWD/get_graph_name_demo.impl \
    $$PWD/get_graph_text_demo.impl \
    $$PWD/get_my_bundled_edge_demo.impl \
    $$PWD/get_my_bundled_edges_demo.impl \
    $$PWD/get_my_bundled_vertex_demo.impl \
    $$PWD/get_my_custom_edge_demo.impl \
    $$PWD/get_my_custom_edges_demo.impl \
    $$PWD/get_my_custom_vertex_demo.impl \
    $$PWD/get_my_custom_vertexes_demo.impl \
    $$PWD/get_n_edges_demo.impl \
    $$PWD/get_n_vertices_demo.impl \
    $$PWD/get_vertex_descriptors_demo.impl \
    $$PWD/get_vertex_iterators_demo.impl \
    $$PWD/get_vertex_name_demo.impl \
    $$PWD/get_vertex_names_demo.impl \
    $$PWD/get_vertex_out_degrees_demo.impl \
    $$PWD/get_vertex_selectedness_demo.impl \
    $$PWD/get_vertex_selectednesses_demo.impl \
    $$PWD/get_vertex_text_demo.impl \
    $$PWD/get_vertex_texts_demo.impl \
    $$PWD/has_bundled_edge_with_my_edge_demo.impl \
    $$PWD/has_bundled_vertex_with_my_vertex_demo.impl \
    $$PWD/has_custom_edge_demo.impl \
    $$PWD/has_custom_edge_with_my_edge_demo.impl \
    $$PWD/has_custom_vertex_demo.impl \
    $$PWD/has_custom_vertex_with_my_vertex_demo.impl \
    $$PWD/has_edge_between_vertices_demo.impl \
    $$PWD/has_edge_with_name_demo.impl \
    $$PWD/has_edge_with_text_demo.impl \
    $$PWD/has_vertex_with_name_demo.impl \
    $$PWD/has_vertex_with_text_demo.impl \
    $$PWD/is_custom_vertices_isomorphic_demo.impl \
    $$PWD/is_isomorphic_demo.impl \
    $$PWD/is_named_vertices_isomorphic_demo.impl \
    $$PWD/is_text_vertices_isomorphic_demo.impl \
    $$PWD/remove_edge_between_vertices_with_names_demo.impl \
    $$PWD/remove_edge_between_vertices_with_texts_demo.impl \
    $$PWD/remove_first_edge_with_name_demo.impl \
    $$PWD/remove_first_edge_with_text_demo.impl \
    $$PWD/remove_first_vertex_with_name_demo.impl \
    $$PWD/remove_first_vertex_with_text_demo.impl \
    $$PWD/remove_nth_vertex_demo.impl \
    $$PWD/remove_selected_custom_edges_and_vertices_demo.impl \
    $$PWD/remove_selected_custom_edges_demo.impl \
    $$PWD/remove_selected_custom_vertices_demo.impl \
    $$PWD/remove_self_loops_demo.impl \
    $$PWD/remove_vertex_if_demo.impl \
    $$PWD/save_bundled_edges_and_vertices_graph_to_dot_demo.impl \
    $$PWD/save_custom_and_selectable_edges_and_vertices_graph_to_dot_demo.impl \
    $$PWD/save_custom_and_selectable_vertices_graph_to_dot_demo.impl \
    $$PWD/save_custom_edges_and_vertices_graph_to_dot_demo.impl \
    $$PWD/save_custom_vertices_graph_to_dot_demo.impl \
    $$PWD/save_graph_to_dot_demo.impl \
    $$PWD/save_named_vertices_graph_to_dot_demo.impl \
    $$PWD/select_random_vertex_demo.impl \
    $$PWD/set_edge_name_demo.impl \
    $$PWD/set_edge_selectedness_demo.impl \
    $$PWD/set_edge_text_demo.impl \
    $$PWD/set_graph_name_demo.impl \
    $$PWD/set_graph_text_demo.impl \
    $$PWD/set_my_bundled_edge_demo.impl \
    $$PWD/set_my_bundled_vertex_demo.impl \
    $$PWD/set_my_custom_edge_demo.impl \
    $$PWD/set_my_custom_vertex_demo.impl \
    $$PWD/set_vertex_name_demo.impl \
    $$PWD/set_vertex_text_demo.impl \
    $$PWD/set_vertex_selectedness_demo.impl
