INCLUDEPATH += $$PWD

include(boost_graph_cookbook_1_graphviz_only_bundled_edges_and_vertices.pri)
include(boost_graph_cookbook_1_graphviz_only_bundled_vertices.pri)
include(boost_graph_cookbook_1_graphviz_only_custom_and_selectable_edges_and_vertices.pri)
include(boost_graph_cookbook_1_graphviz_only_custom_and_selectable_vertices.pri)
include(boost_graph_cookbook_1_graphviz_only_custom_edges_and_vertices.pri)
include(boost_graph_cookbook_1_graphviz_only_custom_vertices.pri)
include(boost_graph_cookbook_1_graphviz_only_helper.pri)
include(boost_graph_cookbook_1_graphviz_only_misc.pri)
include(boost_graph_cookbook_1_graphviz_only_named_and_selectable_vertices.pri)
include(boost_graph_cookbook_1_graphviz_only_named_edges_and_vertices.pri)
include(boost_graph_cookbook_1_graphviz_only_named_graph.pri)
include(boost_graph_cookbook_1_graphviz_only_named_vertices.pri)
include(boost_graph_cookbook_1_graphviz_only_no_properties.pri)
include(boost_graph_cookbook_1_graphviz_only_tutorial.pri)
include(boost_graph_cookbook_1_graphviz_only_unsure.pri)


