include(any_normal.pri)

# Equivalent to:
# include(boost_graph_cookbook_1.pri)

include(boost_graph_cookbook_1_bundled_edges_and_vertices.pri)
include(boost_graph_cookbook_1_bundled_vertices.pri)
include(boost_graph_cookbook_1_custom_and_selectable_edges_and_vertices.pri)
include(boost_graph_cookbook_1_custom_and_selectable_vertices.pri)
include(boost_graph_cookbook_1_custom_edges_and_vertices.pri)
include(boost_graph_cookbook_1_custom_vertices.pri)
include(boost_graph_cookbook_1_helper.pri)
include(boost_graph_cookbook_1_misc.pri)
include(boost_graph_cookbook_1_named_and_selectable_vertices.pri)
include(boost_graph_cookbook_1_named_edges_and_vertices.pri)
include(boost_graph_cookbook_1_named_graph.pri)
include(boost_graph_cookbook_1_named_vertices.pri)
include(boost_graph_cookbook_1_no_properties.pri)
include(boost_graph_cookbook_1_tutorial.pri)

include(boost_graph_cookbook_1_text_edges_and_vertices.pri)
include(boost_graph_cookbook_1_text_vertices.pri)

SOURCES += main.cpp

# USe Graphviz
LIBS += -lboost_graph
