#include "load_undirected_text_edges_and_vertices_graph_from_dot.h"

#ifndef BOOST_GRAPH_COOKBOOK_1_NO_GRAPHVIZ
#include "load_undirected_text_edges_and_vertices_graph_from_dot.impl"
#endif // BOOST_GRAPH_COOKBOOK_1_NO_GRAPHVIZ
