#ifndef SAVE_NAMED_EDGES_AND_VERTICES_GRAPH_TO_DOT
#define SAVE_NAMED_EDGES_AND_VERTICES_GRAPH_TO_DOT

#include "save_text_edges_and_vertices_graph_to_dot.impl"

#endif // SAVE_NAMED_EDGES_AND_VERTICES_GRAPH_TO_DOT

