# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
  pull_request:

name: Build LaTeX document

jobs:
  build_latex:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: boost_graph_cookbook_1.tex
          working_directory: boost_graph_cookbook_1

      - name: Upload PDF to the workflow tab
        uses: actions/upload-artifact@v2
        with:
          name: boost_graph_cookbook_1
          path: boost_graph_cookbook_1.pdf

