on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 2 * *"

name: Build PDF document

jobs:
  build_pdf:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: boost_graph_cookbook_1.tex
          working_directory: boost_graph_cookbook_1

      #- name: Compile LaTeX document
      #  uses: dante-ev/latex-action@latest
      #  with:
      #    root_file: boost_graph_cookbook_1.tex
      #    working_directory: boost_graph_cookbook_1


      - name: Upload PDF to the workflow tab
        uses: actions/upload-artifact@v2
        with:
          name: boost_graph_cookbook_1.pdf
          path: boost_graph_cookbook_1/boost_graph_cookbook_1.pdf

