# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
  pull_request:

name: test_code

jobs:
  test_code:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install Boost
        run: sudo apt install -qq libboost-all-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v3

      - name: Setup ImageMagick
        uses: mfinelli/setup-imagemagick@v1

      - name: qmake tests without graphviz
        run: qmake boost_graph_cookbook_1/boost_graph_cookbook_1_test_no_graphviz.pro

      - name: make tests without graphviz
        run: make --silent debug

      - name: run tests without graphviz
        run: ./boost_graph_cookbook_1_test_no_graphviz

      - name: What do we have here?
        run: ls

      - name: Install codecov
        run: sudo pip install codecov

      - name: Move function notes
        run: |
          cp debug/*.gcda .
          cp debug/*.gcno .
          cp debug/*.o .

      - name: Get code coverage notes
        run : ./get_code_cov.sh >/dev/null

      - name: Get code coverage
        run : codecov >/dev/null

      - name: Submit code coverage to codecov
        run : bash <(curl -s https://codecov.io/bash) > /dev/null

# Not yet
#      - name: Setup Graphviz
#        uses: ts-graphviz/setup-graphviz@v1

#  # gdb
#  - sudo apt install -qq gdb
#  # ImageMagick
#  - sudo apt-get install -qq imagemagick graphviz gsfonts
#  - sudo apt-get install -qq gcc perl libltdl-dev libpng-dev libtiff-dev liblcms2-dev
#  - sudo apt-get install -qq libperl-dev libjpeg62-dev libbz2-dev libwmf-dev libx11-dev libxt-dev libxext-dev libxml2-dev libfreetype6-dev libexif-dev pkg-config
#  # cppcheck
#  - sudo apt install cppcheck
#  # gdb
#  - gdb -v
#  # OCLint
#  - ./install_oclint.sh
#
#script: 
#  - type dot
#  # No GraphViz, test
#  - qmake boost_graph_cookbook_1/boost_graph_cookbook_1_test_no_graphviz.pro
#  - travis_wait 30 make --silent debug
#  - ./boost_graph_cookbook_1_test_no_graphviz
#  # No Graphviz, normal
#  #- qmake boost_graph_cookbook_1/boost_graph_cookbook_1_no_graphviz.pro
#  #- make debug
#  #- ./boost_graph_cookbook_1_no_graphviz
#  # Graphviz, test
#  - qmake boost_graph_cookbook_1/boost_graph_cookbook_1_test.pro
#  - travis_wait 30 make --silent debug
#  - ./boost_graph_cookbook_1_test
#  # Graphviz, normal
#  #- qmake boost_graph_cookbook_1/boost_graph_cookbook_1.pro
#  #- make --silent debug
#  #- ./boost_graph_cookbook_1
#  # cppcheck
#  - cppcheck --quiet --error-exitcode=1 . 
#  # Call OCLint, takes to long...
#  # - travis_wait 60 ./do_oclint.sh
#
#
#after_failure:
#  - pdflatex -v
#  - cd ~; find . | egrep "\.tex"
#  - cd ~; find . | egrep "\.log"
#  - cd /usr; find . | egrep "/texlive$"
#  - cd /opt; find . | egrep "/texlive$"
#  - cd /; find . | egrep "/texlive$"
#  #- which tlmgr
#  - echo $PATH
#  - cat /home/travis/build/richelbilderbeek/boost_graph_cookbook_1/boost_graph_cookbook_1/boost_graph_cookbook_1.tex
#
